kind: Deployment
apiVersion: apps/v1
metadata:
  name: spoke-scalar-agent
  labels:
    app: spoke-scalar-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoke-scalar-agent
  template:
    metadata:
      labels:
        app: spoke-scalar-agent
    spec:
      serviceAccountName: spoke-scalar-agent-sa
      containers:
      - name: spoke-scalar-agent
        image: quay.io/haoqing/scalar-agent:latest
        imagePullPolicy: Always
        args:
          - "/scalaragent"
          - "agent"
          - "--cluster-name=cluster1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - name: hub-kubeconfig
          mountPath: "/spoke/hub-kubeconfig"
      volumes:
      - name: hub-kubeconfig
        emptyDir:
          medium: Memory
      volumes:
      - name: hub-kubeconfig
        secret:
          secretName: hub-kubeconfig-secret