apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: open-cluster-management:scalar-agent
  namespace: open-cluster-management-agent
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
#- apiGroups: [""]
#  resources: ["pods"]
#  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
#- apiGroups: [""]
#  resources: ["configmaps", "secrets"]
#  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
#- apiGroups: ["", "events.k8s.io"]
#  resources: ["events"]
#  verbs: ["create", "patch", "update"]
#